using SimpLog.Databases.Oracle.Models.AppSettings;
using System.Text;

namespace SimpLog.Databases.Oracle.Services.DatabaseServices
{
    internal class DatabaseMigrations
    {
        public static Configuration conf = ConfigurationServices.ConfigService.BindConfigObject();

        public static void CreateOracleIfNotExists()
        {
            StringBuilder query = new StringBuilder();
            query.Append($" create table if not exists StoreLog ");
            query.Append($"    ( ");
            query.Append($"    \"{"ID"}\" number GENERATED BY DEFAULT AS IDENTITY ");
            query.Append($"   ,\"{"Log_Type"}\" varchar(50) ");
            query.Append($"   ,\"{"Log_Error"}\" varchar(50) ");
            query.Append($"   ,\"{"Log_Created"}\" varchar(50) ");
            query.Append($"   ,\"{"Log_FileName"}\" varchar(50) ");
            query.Append($"   ,\"{"Log_Path"}\" varchar(50) ");
            query.Append($"   ,\"{"Log_SendEmail"}\" char(1) ");
            query.Append($"   ,\"{"Email_ID"}\" number ");
            query.Append($"   ,\"{"Saved_In_Database"}\" varchar(50) ");
            query.Append($"    ); ");

            query.Append($" create table if not exists EmailLog ");
            query.Append($"    ( ");
            query.Append($"    \"{"ID"}\" number GENERATED BY DEFAULT AS IDENTITY ");
            query.Append($"   ,\"{"From_Email"}\" varchar(50) ");
            query.Append($"   ,\"{"To_Email"}\" varchar(50) ");
            query.Append($"   ,\"{"Bcc"}\" varchar(50) ");
            query.Append($"   ,\"{"Email_Subject"}\" varchar(50) ");
            query.Append($"   ,\"{"Email_Body"}\" varchar(50) ");
            query.Append($"   ,\"{"Time_Sent"}\" varchar(50) ");
            query.Append($"    ); ");
        }
    }
}
